### ISSUE TITLE
GPIO panel: connection: Unknown error

### ISSUE THREAD

**Issue by smuehlst** [flypie/flypie-pi-qemu#1]
I followed the build and run instructions from https://github.com/rsta2/circle/issues/34 closely but not exactly.

Note that my cygwin HOME directory name contains a blank against your advice as I could not avoid this, but I made sure that the qemu repository and the build directory pathnames do not contain  blanks.

I have set up cygwin and installed the following mingw64 packages:

    $ cygcheck -c | grep mingw
    mingw64-x86_64-binutils                 2.25.0.1.23f238d-1     OK
    mingw64-x86_64-gcc-core                 5.4.0-3                OK
    mingw64-x86_64-gcc-g++                  5.4.0-3                OK
    mingw64-x86_64-gettext                  0.19.8.1-2             OK
    mingw64-x86_64-glib2.0                  2.50.3-1               OK
    mingw64-x86_64-headers                  5.0.2-1                OK
    mingw64-x86_64-libffi                   3.2.1-2                OK
    mingw64-x86_64-pcre                     8.40-3                 OK
    mingw64-x86_64-pkg-config               0.29.1-1               OK
    mingw64-x86_64-runtime                  5.0.2-1                OK
    mingw64-x86_64-win-iconv                0.0.6-2                OK
    mingw64-x86_64-windows-default-manifest 6.4-1                  OK
    mingw64-x86_64-winpthreads              5.0.2-1                OK
    mingw64-x86_64-zlib                     1.2.11-1               OK

Cloned  the git repository and checked out subrepositories:

    $ cd /home/stm/git
    $ git clone https://github.com/flypie/flypie-pi-qemu.git
    $ cd  flypie-pi-qemu
    $ git submodule update --init dtc pixman

Built in a separate directory side-by-side with the repository as I want to keep the git repository directory tree clean:

    $ mkdir /home/stm/git/flypie-pi-qemu-build
    $ cd /home/stm/git/flypie-pi-qemu-build
    $ ../flypie-pi-qemu/configure --disable-libusb --cc=x86_64-w64-mingw32-gcc.exe --cxx=x86_64-w64-mingw32-g++.exe  --cross-prefix=x86_64-w64-mingw32-  --target-list=arm-softmmu --disable-usb-redir --extra-cflags="-static-libgcc -static-libstdc++ -ggdb"
    $ make

The build is successful. For being able to run the qemu-system-arm.exe executable I have to extend the PATH:

    $ export PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin:$PATH

Otherwise libwinpthread-1.dll is unresolved when I try to run `qemu-system-arm.exe`.

Now  qemu-system-arm.exe works in general, for example with option "--help" I'm seeing the list of command line options.

When I try to launch a Circle kernel, the following happens:

    $ SDL_VIDEODRIVER=windib QEMU_AUDIO_DRV=dsound SDL_AUDIODRIVER=dsound QEMU_AUDIO_LOG_TO_MONITOR=1 ./qemu-system-arm -machine raspi2 -smp 1 -bios /cygdrive/e/Users/stm/Documents/GitHub/circle/sample/03-screentext/kernel7.img -usbdevice keyboard
    GPIO panel: connection: Unknown error
    Couldn't connect to a GPIO panel
    C:\cygwin64\home\stm\git\flypie-pi-qemu-build\arm-softmmu\qemu-system-arm.exe: Failed to load firmware from /cygdrive/e/Users/stm/Documents/GitHub/circle/sample/03-screentext/kernel7.img

I noticed that in your batch files to launch qemu you are changing the working directory to `C:/qemu`. What is the significance of this?

Thanks!

**Comment by flypie** [comment]
I don't think 
"GPIO panel: connection: Unknown error
Couldn't connect to a GPIO panel"
 and the failed to load are connected. That just a message indicating that GDummyPanel wasn't running.
The significance of the "cd c:\qemu" is that I had problems assembling all the dll files etc. So I ended up doing and install of the latest mainstream QEMU and the CDing into that to make sure all the relevant files where there. You should try this.

**Comment by smuehlst** [comment]
I installed that latest mainstream QEMU as suggested into C:\QEMU and started the qemu built from your repo in the same manner as in your script `pirun2.bat` from a Windows command prompt, after adding `C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\bin` to the PATH variable. Now it looks better:

    C:\QEMU>C:\cygwin64\home\stm\flypie-pi-qemu-inst\qemu-system-arm.exe -machine raspi2 -smp 1 -bios E:\Users\stm\Documents\GitHub\circle\sample\03-screentext\kernel7.img  -usbdevice keyboard
    GPIO panel: connection: Unknown error
    Couldn't connect to a GPIO panel
    VNC server running on ::1:5900

So now the kernel image is loaded successfully apparently. Is it the expected behavior that the VNC server is started? From your [demo2 video](https://www.youtube.com/watch?v=eu8H8R85Zik) it now became clear to me that I need to build the [GDummyPanel](https://github.com/flypie/GDummyPanel) application with Visual Studio. But the video does not make clear how the QEMU window is opened. Can you elaborate how you are starting it?

**Comment by flypie** [comment]
I'm sorry I've never used VNC with QEMU. I think starting is the same. https://www.cyberciti.biz/faq/linux-kvm-vnc-for-guest-machine/

**Comment by smuehlst** [comment]
Well I'm wondering why it starts a VNC server instead of opening a console window as in your demo video. It's not that I want to use VNC, and I gave no command line option that told it to start VNC server.
As a side note, as I have installed the full official QEMU distribution now I tried to run a Circle kernel directly with the official QEMU, and it seems to work, at least the sample 3 that you also did show in  https://github.com/rsta2/circle/issues/34.
So do I understand it correctly that the main difference between your fork and the official QEMU is the emulation of the GPIO pins?

**Comment by flypie** [comment]
It sounds like they have updated the QEMU root a bit to incorporate the PI elements. There are some other differences I think but should be minor.
With VNC I can only assume it is some of the environment variables I set in the batch files to run or perhaps some other software you have installed. The main use of QEMU in VNC mode is when it is running on headless machines.

**Comment by smuehlst** [comment]
I could not find out how to get an output window instead of the VNC connection when starting qemu-system-arm.exe. As I don't currently work on programs that use GPIO the official QEMU seems to be good enough for me at the moment, so for the time being I won't bother you further. Thanks!
